<script type="text/javascript">
//<![CDATA[
    
    var BASE_URL = '<?php echo Mage::getBaseUrl() ?>';

    if(window.location.href.match('https://') && !BASE_URL.match('https://')){
        BASE_URL = BASE_URL.replace('http://', 'https://')
    }

	var AUTOCOMPLETE_URL_STREET = BASE_URL + "postcode/finder/autocomplete";
	var AUTOCOMPLETE_URL_BUILDING = BASE_URL + "postcode/finder/autocomplete_building";
	
    new Ajax.Autocompleter("meanbee:billing_autocomplete", "autocomplete_choices_billing_street", AUTOCOMPLETE_URL_STREET, {
        minChars: 2,  
        indicator: 'indicator_billing_street',
        paramName: 'street',
        callback: getCountryAndPostcodeBilling,
        afterUpdateElement: postcode_autocomplete_selected
    });

    new Ajax.Autocompleter("meanbee:shipping_autocomplete", "autocomplete_choices_shipping_street", AUTOCOMPLETE_URL_STREET, {
        minChars: 2,
        indicator: 'indicator_shipping_street',
        paramName: 'street',
        callback: getCountryAndPostcodeShipping,
        afterUpdateElement: postcode_autocomplete_selected
    }); 
    
    new Ajax.Autocompleter("meanbee:billing_autocomplete_building", "autocomplete_choices_billing_building", AUTOCOMPLETE_URL_BUILDING, {
        minChars: 2,  
        indicator: 'indicator_billing_building',
        paramName: 'building',
        callback: getStreet,
        afterUpdateElement: postcode_autocomplete_building
    });

    new Ajax.Autocompleter("meanbee:shipping_autocomplete_building", "autocomplete_choices_shipping_building", AUTOCOMPLETE_URL_BUILDING, {
        minChars: 2,
        indicator: 'indicator_shipping_building',
        paramName: 'building',
        callback: getStreet,
        afterUpdateElement: postcode_autocomplete_building
    });  

    /* Set default country (Optional) */
    $('billing:country_id').value = 'GB';
    billingRegionUpdater.update();
 
    $('shipping:country_id').value = 'GB';
    shippingRegionUpdater.update();

    /* Activate the listeners */
    postcode_observe('billing');
    postcode_observe('shipping');

//]]>
</script>
