<script type="text/javascript">
//<![CDATA[
    /* Set default country (Optional) */
    $('billing:country_id').value = 'GB';
    billingRegionUpdater.update();
		
    $('shipping:country_id').value = 'GB';
    shippingRegionUpdater.update();
		
    var BASE_URL = '<?php echo $this->getUrl()?>';
	
    new Ajax.Autocompleter("meanbee:billing_autocomplete", "autocomplete_choices", BASE_URL + "postcode/finder/autocomplete", {
        minChars: 2,  
        indicator: 'indicator',
        paramName: 'street',
        callback: getCountryAndPostcodeBilling,
        afterUpdateElement: postcode_fillFieldsWorld
    });

    new Ajax.Autocompleter("meanbee:shipping_autocomplete", "autocomplete_choices", BASE_URL + "postcode/finder/autocomplete", {
        minChars: 2,
        indicator: 'indicator',
        paramName: 'street',
        callback: getCountryAndPostcodeShipping,
        afterUpdateElement: postcode_fillFieldsWorld
    });	

    /* Activate the listeners */
	postcode_observe('billing');
	postcode_observe('shipping');
//]]>
</script>
