<?php if($this->getIsShipping()):
    $_formId = 'shipping';
    $_FormId = 'Shipping';
else:
    $_formId = 'billing';
    $_FormId = 'Billing';
endif; ?>

<div class="meanbee_address_finder entry-edit">
    <div class="entry-edit-head">
        <h4>Meanbee Address Finder</h4>
    </div>
    <div class="order-address">
        <fieldset class="np">
            <table class="form-list" cellspacing="0">
                <tbody>
                    <tr>
                        <td class="label">
                            <label for="<?php echo $_formId ?>:country_id"><?php echo $this->__('Country') ?></label>
                        </td> 
                        <td class="value">           
                            <?php echo Mage::getBlockSingleton('directory/data')
                                ->getCountryHtmlSelect(null, $_formId . '[country_id]',$_formId . ':country_id','Country' ) ?>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td class="value">
                            <span id="meanbee_smart_address_info_<?php echo $_formId ?>"></span>  
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            <label for="<?php echo $_formId ?>:postcode"><?php echo $this->__('Enter Postcode:') ?></label>
                        </td>
                        <td class="value">
                            <input class="input-text" type="text" title="<?php echo $this->__('Post Code') ?>" id="<?php echo $_formId ?>:postcode">
                            <button id="meanbee:<?php echo $_formId ?>_address_find" type="button">Find Address</button>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td class="value">
                            <ul>
                                <li id="meanbee:<?php echo $_formId ?>_address_selector">&nbsp;</li>
                            </ul>
                        <td>
                    </tr>
                </tbody>
            </table>
            <div id="meanbee:<?php echo $_formId ?>_street">
                <table class="form-list" cellspacing="0">
                    <tbody>
                        <tr>
                            <td class="label">    
                                <label for="meanbee:<?php echo $_formId ?>_autocomplete"><?php echo $this->__('Street (Start typing...)') ?></label>
                            </td>
                            <td class="value">
                                <input type="text" title="Start typing street" id="meanbee:<?php echo $_formId ?>_autocomplete" name="autocomplete_parameter" class="input-text"/>
                                <span id="indicator_<?php echo $_formId ?>_street" style="display: none">
                                </span>
                                <div id="autocomplete_choices_<?php echo $_formId ?>_street" class="autocomplete" style="z-index:99999"></div>
                            </td>
                        </tr>
                    </tbody>
               </table>
               </div>
               <div id="meanbee:<?php echo $_formId ?>_building">
               <table class="form-list" cellspacing="0">
                    <tbody>
                        <tr>
                            <td class="label">
                                <label for="meanbee:<?php echo $_formId ?>_autocomplete_building"><?php echo $this->__('Building (Start typing...)') ?></label>
                            </td>
                            <td class="value">
                                <input type="text" title="Start typing building" id="meanbee:<?php echo $_formId ?>_autocomplete_building" name="autocomplete_parameter" class="input-text" />
                                <span id="indicator_<?php echo $_formId ?>_building" style="display: none">
                                </span>
                                <div id="autocomplete_choices_<?php echo $_formId ?>_building" class="autocomplete" style="z-index:99999"></div>
                            </td>
                    </tr>
                </tbody>
            </table>
            </div>
        </fieldset>
    </div>
</div>
<?php echo $this->getChildHtml('magento_' . $_formId . '_address') ?>
<script type="text/javascript">
//<![CDATA[

    var BASE_URL = '<?php echo Mage::getBaseUrl() ?>';

    if(window.location.href.match('https://') && !BASE_URL.match('https://')){
        BASE_URL = BASE_URL.replace('http://', 'https://')
    }

    var AUTOCOMPLETE_URL_STREET = BASE_URL + "postcode/finder/autocomplete";
    var AUTOCOMPLETE_URL_BUILDING = BASE_URL + "postcode/finder/autocomplete_building";
    
    new Ajax.Autocompleter("meanbee:<?php echo $_formId ?>_autocomplete", "autocomplete_choices_<?php echo $_formId ?>_street", AUTOCOMPLETE_URL_STREET, {
        minChars: 2,  
        indicator: 'indicator_<?php echo $_formId ?>_street',
        paramName: 'street',
        callback: getCountryAndPostcode<?php echo $_FormId ?>,
        afterUpdateElement: postcode_autocomplete_selected
    });

    new Ajax.Autocompleter("meanbee:<?php echo $_formId ?>_autocomplete_building", "autocomplete_choices_<?php echo $_formId ?>_building", AUTOCOMPLETE_URL_BUILDING, {
        minChars: 2,  
        indicator: 'indicator_<?php echo $_formId ?>_building',
        paramName: 'building',
        callback: getStreet,
        afterUpdateElement: postcode_autocomplete_building
    });

    /* Activate the listeners */
    postcode_observe('<?php echo $_formId ?>');

//]]>
</script>
